name = ("Name : Takdanai")
lastname = ("Lastname : Bussabong")
Nickname = ("Nick ; Muaytu")
hello = ("hello M.6/11")
Age = ("อายุ : 17 ปี")
Facebook = ("facebook : Takedanai Bussabong")
Instagram =("Instagram : muayza.xd")
tel = ("เบอร์โทร : 0953750220")
Hobby = ("งานอดิเรก:เล่นกีตาร์")
School =("โรงเรียน:ชลราษฎรอำรุง")
print(name)
print(lastname)
print(Nickname)
print(hello)
print(Age)
print(Facebook)
print(Instagram)
print(tel)
print(Hobby)
print(School)
#ทักษ์ดนัย บุษบง เลขที่ 3 ชั้น ม.6/11