print("hello M.6/11")
print("My name is Muaytu")
print("No.3")
print("Name : Takdanai")
print("Lastname : Bussabong")
print("Nick ; Muaytu")
print("hello M.6/11")
print("อายุ : 17 ปี")
print("facebook : Takedanai Bussabong")
print("Instagram : muayza.xd")
print("เบอร์โทร : 0953750220")
print("งานอดิเรก:เล่นกีตาร์")
print("โรงเรียน:ชลราษฎรอำรุง")